routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/all_questionnaire', 'MainController')->names('questionnaire');

Route::get('/deleteImage', 'MainController@deleteImage');

app/Models/Questionnaire.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Questionnaire extends Model
{
    /**
     * @var string[]
     */
    protected $fillable = [
        'name',
        'file'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreRequest;
use App\Http\Requests\UpdateRequest;
use App\Models\Questionnaire;
use App\Service\QuestionnaoreService;
use Illuminate\Http\Request;

class MainController extends Controller
{

    protected $service;

    /**
     * MainController constructor.
     */
    public function __construct()
    {
        $this->service = app(QuestionnaoreService::class);
    }
    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $questionnaires = Questionnaire::paginate(5);

        return view('all_questionnaire', compact('questionnaires'));
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return  view('create_questionnaire');
    }

    /**
     * @param StoreRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreRequest $request)
    {
        $data = $request->passedValidation();

        Questionnaire::create($data);

        return redirect()->route('questionnaire.index')->with(['success' => 'Анкета успішно збережена']);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $questionnaire = Questionnaire::find($id);
        $count = count(json_decode($questionnaire->file, true) ?? []);

        return view('show', compact('questionnaire', 'count'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $questionnaire = Questionnaire::find($id);

        return view('edit', compact('questionnaire'));
    }

    /**
     * @param UpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, $id)
    {
        $data = $request->passedValidation();
        $questionnaire = Questionnaire::find($id);
        $file = json_decode($questionnaire->file,true);
        $updateFile = array_merge($file,$data['file']);
        $questionnaire->name = $data['name'];
        $questionnaire->file = json_encode($updateFile);
        $questionnaire->save();

        return back()->with(['success' => 'Дані оновленні']);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $questionnaire = Questionnaire::find($id)->delete();
        if ($questionnaire){
            return back()->with(['success' => 'Успішно видалено']);
        }
        return back()->withErrors(['error' => 'Помилка видалення']);

    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     */
    public function deleteImage(Request $request)
    {
        if ($request->ajax()){
            $data  = $request->request->get('data');
             $result =  $this->service->deleteImage($data);
             if ($result){
                 return response('success',200);
             } else {
                 return response('error',500);
             }
        }
    }
}

resources/views/all_questionnaire.blade.php
@extends('layouts.main')

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="card-title"><span class="font-weight-bold">Всі Анкети</span></div>
        </div>
        @if(session('success'))
            <div class="row justify-content-center">
                <div class="col-md-3">
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">x</span>
                        </button>
                        {{ session()->get('success') }}
                    </div>
                </div>
            </div>
        @endif
        @if($errors->any())
            <div class="row justify-content-center">
                <div class="col-md-11">
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">x</span>
                        </button>
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif
        <div class="card-body">
            <a href="{{route('questionnaire.create')}}" class="btn btn-outline-info mb-2">Створити</a>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ім'я</th>
                    <th scope="col">Зображення</th>
                    <th scope="col">Редагувати</th>
                    <th scope="col">Видалити</th>
                </tr>
                </thead>
                <tbody>
                @foreach($questionnaires as $key => $questionnaire)
                <tr>
                    <th scope="row">{{$key + 1}}</th>
                    <td><a href="{{route('questionnaire.show',$questionnaire->id)}}">{{{$questionnaire->name}}}</a></td>
                    <td>
                        @if($questionnaire->file)
                            <img src="{{asset('/storage/'.json_decode($questionnaire->file, true)['0'])}}" alt="" class="img-thumbnail" width="100px" >
                        @else
                            <img src="http://dummyimage.com/150x60/99cccc.jpg/0b0b0b&text=The+image!" />
                        @endif

                    </td>
                    <td><a href="{{route('questionnaire.edit',$questionnaire->id)}}" class="btn btn-sm btn-outline-primary">edit</a></td>
                    <td>
                        <form action="{{route('questionnaire.destroy',$questionnaire->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-sm btn-danger">-</button>
                        </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>
            @if($questionnaires->total() > $questionnaires->count())
                <br>
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                {{$questionnaires->links()}}
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>
@endsection

resources/views/create_questionnaire.blade.php
@extends('layouts.main')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('questionnaire.index')}}">Назад до списку</a></li>
            <li class="breadcrumb-item">Створення нової анкети</li>
        </ol>
    </nav>

    <div class="container">
        <div class="card">
            <div class="card-title text-center"><span class="text-danger">*</span> Поля обовязкові для заповннення</div>
            <div class="card-body">
                <form method="POST" action="{{route('questionnaire.store')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label><span class="text-danger">*</span> Ім'я</label>
                        <input name="name" type="text" class="form-control col-4 @error('name') is-invalid @enderror" value="{{old('name')}}" required>
                        <small class="form-text text-muted">Введіть ваше ім'я</small>
                        @error('name')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Зображення</label>
                        <input name="file[]" type="file" class="form-control-file @error('file') is-invalid @enderror" multiple>

                        @error('file.*')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-outline-primary">Зберегти</button>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/edit.blade.php
@extends('layouts.main')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('questionnaire.index')}}">Назад до списку</a></li>
            <li class="breadcrumb-item">Редагування анкети</li>
        </ol>
    </nav>

    <div class="container">
        <div class="card">
            <div class="card-title text-center"><span class="text-danger">*</span> Поля обовязкові для заповннення</div>
            <div class="card-body">
                <form method="POST" action="{{route('questionnaire.update',$questionnaire->id)}}" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    @if(session('success'))
                        <div class="row justify-content-center">
                            <div class="col-md-3">
                                <div class="alert alert-success" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">x</span>
                                    </button>
                                    {{ session()->get('success') }}
                                </div>
                            </div>
                        </div>
                    @endif
                    <div class="form-group">
                        <label><span class="text-danger">*</span> Ім'я</label>
                        <input name="name" type="text" class="form-control col-4 @error('name') is-invalid @enderror" value="{{old('name') ?? $questionnaire->name}}" required>
                        <small class="form-text text-muted">Введіть ваше ім'я</small>
                        @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label><span class="text-danger">*</span> Зображення</label>
                        @foreach(json_decode($questionnaire->file, true) ?? [] as $key => $path)
                            <div>
                                <img src="{{asset('/storage/'.$path)}}" class="img-thumbnail" width="100px" alt="..."> <button type="button" class="btn btn-sm btn-danger" data-info="{{$path}}" data-id="{{$questionnaire->id}}" onclick="deleteImage(this)">--</button>
                            </div>
                        @endforeach
                    </div>
                    <div class="form-group">
                        <label>Додати зображення</label>
                        <input name="file[]" type="file" class="form-control-file @error('file') is-invalid @enderror" multiple>

                        @error('file.*')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-outline-primary">Зберегти</button>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PandaTeam</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
    <link href="{{asset('css/css/all.css')}}" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="stylesheets/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="{{asset('js/app.js')}}"></script>
    <script src="{{asset('js/main.js')}}"></script>
</head>
<body>
<div class="container">
    @yield('content')
</div>
</body>
</html>

resources/views/show.blade.php
@extends('layouts.main')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('questionnaire.index')}}">Назад до списку</a></li>
            <li class="breadcrumb-item">Перегляд анкети</li>
        </ol>
    </nav>
    @if(session('success'))
        <div class="row justify-content-center">
            <div class="col-md-3">
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">x</span>
                    </button>
                    {{ session()->get('success') }}
                </div>
            </div>
        </div>
    @endif
    <div class="card">
        <div class="card-header">
            <div class="card-title"><span class="font-weight-bold">{{$questionnaire->name}}</span></div>
        </div>
        <div class="card-body">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    @for($j = 0;$j < $count; $j++)
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{$j}}" @if($j == 0) class="active"@endif></li>
                    @endfor
                </ol>
                <div class="carousel-inner">
                    @foreach(json_decode($questionnaire->file, true) ?? [] as $key => $path)
                        <div class="carousel-item @if($key == 0) active  @endif">
                            <img src="{{asset('/storage/'.$path)}}" class="d-block w-100" alt="...">
                        </div>
                    @endforeach
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
@endsection